version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/Siddu-Pension-TD:1"
        LoadBalancerInfo:
          ContainerName: "siddu-jwt"
          ContainerPort: "9085"
        PlatformVersion: "LATEST"
